name: test Report
on: [push]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate HTML report
        run: 
          mkdir -p html_report
          echo "<h1>Hello Report</h1><p>This is a test.</p>" > html_report/index.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html_report
          path: html_report/
