name: forTest

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04  # self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run test
        run: |
          echo "=======it's a test========="
          echo "run number=$GITHUB_RUN_NUMBER"
          echo "run_id=$GITHUB_RUN_ID"
          echo "hostname=$(hostname)"
          echo "whoami=$(whoami)"
          echo "curpath=$(pwd)"
          echo "---------------------------------------"
          export -p
          echo "------------------end"
